### ISSUE TITLE
ImportError: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by johnhbenetech** [dOpensource/dsiprouter#429]
Following the Debian installation instructions, my installation fails near the end of the dSIP part of the installation pipeline with the following error:

```
Configuring dSIPRouter settings
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/dsiprouter/gui/util/security.py", line 10, in <module>
    from shared import updateConfig,StatusCodes
  File "/opt/dsiprouter/gui/shared.py", line 8, in <module>
    from flask import request, render_template, make_response, jsonify
  File "/usr/local/lib/python3.7/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.7/dist-packages/jinja2/__init__.py)
Resetting credentials
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/dsiprouter/gui/util/security.py", line 10, in <module>
    from shared import updateConfig,StatusCodes
  File "/opt/dsiprouter/gui/shared.py", line 8, in <module>
    from flask import request, render_template, make_response, jsonify
  File "/usr/local/lib/python3.7/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.7/dist-packages/jinja2/__init__.py)
Credentials have been updated
Setting credentials
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/dsiprouter/gui/util/security.py", line 10, in <module>
    from shared import updateConfig,StatusCodes
  File "/opt/dsiprouter/gui/shared.py", line 8, in <module>
    from flask import request, render_template, make_response, jsonify
  File "/usr/local/lib/python3.7/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.7/dist-packages/jinja2/__init__.py)
Failed setting encrypted credentials
```

**Comment by johnhbenetech** [comment]
confirmed fixed in branch
